### ISSUE TITLE
On new installation, the instructions in README.md are inadequate.

### ISSUE THREAD

**Issue by haxys** [TorSpider/TorSpider-Backend#18]
Following step-by-step with a fresh PostgreSQL system, the `initdb` and `seed` commands work flawlessly, but when I try to start the server with `python3 backend_manage.py run` the script crashes with the following error:

```
Traceback (most recent call last):
  File "backend_manage.py", line 198, in <module>
    manager.run()
  File "/home/chris/TorSpider/backend/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/chris/TorSpider/backend/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/chris/TorSpider/backend/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "backend_manage.py", line 65, in run
    app.run(host=addr, port=port, threaded=True, ssl_context=context)
  File "/home/chris/TorSpider/backend/venv/lib/python3.5/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/chris/TorSpider/backend/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/home/chris/TorSpider/backend/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/home/chris/TorSpider/backend/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 660, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/chris/TorSpider/backend/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 601, in __init__
    self.socket = ssl_context.wrap_socket(sock, server_side=True)
  File "/home/chris/TorSpider/backend/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 511, in wrap_socket
    ssl_version=self._protocol, **kwargs)
  File "/usr/lib/python3.5/ssl.py", line 1069, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.5/ssl.py", line 691, in __init__
    self._context.load_cert_chain(certfile, keyfile)
FileNotFoundError: [Errno 2] No such file or directory
```

It would appear that a certificate is required. Instructions need to be added regarding how to create or obtain this certificate and where to put it.

**Comment by artagel** [comment]
Also if you set the usetls flag to false in the config it won’t try to use it.
